[tool.poetry]
name = "wizard"
version = "0.1.0"
description = ""
authors = ["DevSmapy <lyk456@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyspark = "^3.5.1"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
